apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oo2yrkf7f-python 
  janus-idp.io/tekton: oo2yrkf7f-python
  backstage.io/kubernetes-id: oo2yrkf7f-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oo2yrkf7f-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml